<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->char('id', 2)->index();
            $table->string('description');
            $table->boolean('active')->default(true);
        });

        DB::table('countries')->insert([
            ['id' => 'AX', 'description' => 'AALAND ISLANDS'],
            ['id' => 'AF', 'description' => 'AFGHANISTAN'],
            ['id' => 'AL', 'description' => 'ALBANIA'],
            ['id' => 'DZ', 'description' => 'ALGERIA'],
            ['id' => 'AS', 'description' => 'AMERICAN SAMOA'],
            ['id' => 'AD', 'description' => 'ANDORRA'],
            ['id' => 'AO', 'description' => 'ANGOLA'],
            ['id' => 'AI', 'description' => 'ANGUILLA'],
            ['id' => 'AQ', 'description' => 'ANTARCTICA'],
            ['id' => 'AG', 'description' => 'ANTIGUA AND BARBUDA'],
            ['id' => 'AR', 'description' => 'ARGENTINA'],
            ['id' => 'AM', 'description' => 'ARMENIA'],
            ['id' => 'AW', 'description' => 'ARUBA'],
            ['id' => 'AU', 'description' => 'AUSTRALIA'],
            ['id' => 'AT', 'description' => 'AUSTRIA'],
            ['id' => 'AZ', 'description' => 'AZERBAIJAN'],
            ['id' => 'BS', 'description' => 'BAHAMAS'],
            ['id' => 'BH', 'description' => 'BAHRAIN'],
            ['id' => 'BD', 'description' => 'BANGLADESH'],
            ['id' => 'BB', 'description' => 'BARBADOS'],
            ['id' => 'BY', 'description' => 'BELARUS'],
            ['id' => 'BE', 'description' => 'BELGIUM'],
            ['id' => 'BZ', 'description' => 'BELIZE'],
            ['id' => 'BJ', 'description' => 'BENIN'],
            ['id' => 'BM', 'description' => 'BERMUDA'],
            ['id' => 'BT', 'description' => 'BHUTAN'],
            ['id' => 'BO', 'description' => 'BOLIVIA'],
            ['id' => 'BA', 'description' => 'BOSNIA AND HERZEGOWINA'],
            ['id' => 'BW', 'description' => 'BOTSWANA'],
            ['id' => 'BV', 'description' => 'BOUVET ISLAND'],
            ['id' => 'BR', 'description' => 'BRAZIL'],
            ['id' => 'IO', 'description' => 'BRITISH INDIAN OCEAN TERRITORY'],
            ['id' => 'BN', 'description' => 'BRUNEI DARUSSALAM'],
            ['id' => 'BG', 'description' => 'BULGARIA'],
            ['id' => 'BF', 'description' => 'BURKINA FASO'],
            ['id' => 'BI', 'description' => 'BURUNDI'],
            ['id' => 'KH', 'description' => 'CAMBODIA'],
            ['id' => 'CM', 'description' => 'CAMEROON'],
            ['id' => 'CA', 'description' => 'CANADA'],
            ['id' => 'CV', 'description' => 'CAPE VERDE'],
            ['id' => 'KY', 'description' => 'CAYMAN ISLANDS'],
            ['id' => 'CF', 'description' => 'CENTRAL AFRICAN REPUBLIC'],
            ['id' => 'TD', 'description' => 'CHAD'],
            ['id' => 'CL', 'description' => 'CHILE'],
            ['id' => 'CN', 'description' => 'CHINA'],
            ['id' => 'CX', 'description' => 'CHRISTMAS ISLAND'],
            ['id' => 'CC', 'description' => 'COCOS (KEELING) ISLANDS'],
            ['id' => 'CO', 'description' => 'COLOMBIA'],
            ['id' => 'KM', 'description' => 'COMOROS'],
            ['id' => 'CD', 'description' => 'CONGO, Democratic Republic of (was Zaire)'],
            ['id' => 'CG', 'description' => 'CONGO, Republic of'],
            ['id' => 'CK', 'description' => 'COOK ISLANDS'],
            ['id' => 'CR', 'description' => 'COSTA RICA'],
            ['id' => 'CI', 'description' => 'COTE D`IVOIRE'],
            ['id' => 'HR', 'description' => 'CROATIA (local name: Hrvatska)'],
            ['id' => 'CU', 'description' => 'CUBA'],
            ['id' => 'CY', 'description' => 'CYPRUS'],
            ['id' => 'CZ', 'description' => 'CZECH REPUBLIC'],
            ['id' => 'DK', 'description' => 'DENMARK'],
            ['id' => 'DJ', 'description' => 'DJIBOUTI'],
            ['id' => 'DM', 'description' => 'DOMINICA'],
            ['id' => 'DO', 'description' => 'DOMINICAN REPUBLIC'],
            ['id' => 'EC', 'description' => 'ECUADOR'],
            ['id' => 'EG', 'description' => 'EGYPT'],
            ['id' => 'SV', 'description' => 'EL SALVADOR'],
            ['id' => 'GQ', 'description' => 'EQUATORIAL GUINEA'],
            ['id' => 'ER', 'description' => 'ERITREA'],
            ['id' => 'EE', 'description' => 'ESTONIA'],
            ['id' => 'ET', 'description' => 'ETHIOPIA'],
            ['id' => 'FK', 'description' => 'FALKLAND ISLANDS (MALVINAS)'],
            ['id' => 'FO', 'description' => 'FAROE ISLANDS'],
            ['id' => 'FJ', 'description' => 'FIJI'],
            ['id' => 'FI', 'description' => 'FINLAND'],
            ['id' => 'FR', 'description' => 'FRANCE'],
            ['id' => 'GF', 'description' => 'FRENCH GUIANA'],
            ['id' => 'PF', 'description' => 'FRENCH POLYNESIA'],
            ['id' => 'TF', 'description' => 'FRENCH SOUTHERN TERRITORIES'],
            ['id' => 'GA', 'description' => 'GABON'],
            ['id' => 'GM', 'description' => 'GAMBIA'],
            ['id' => 'GE', 'description' => 'GEORGIA'],
            ['id' => 'DE', 'description' => 'GERMANY'],
            ['id' => 'GH', 'description' => 'GHANA'],
            ['id' => 'GI', 'description' => 'GIBRALTAR'],
            ['id' => 'GR', 'description' => 'GREECE'],
            ['id' => 'GL', 'description' => 'GREENLAND'],
            ['id' => 'GD', 'description' => 'GRENADA'],
            ['id' => 'GP', 'description' => 'GUADELOUPE'],
            ['id' => 'GU', 'description' => 'GUAM'],
            ['id' => 'GT', 'description' => 'GUATEMALA'],
            ['id' => 'GN', 'description' => 'GUINEA'],
            ['id' => 'GW', 'description' => 'GUINEA-BISSAU'],
            ['id' => 'GY', 'description' => 'GUYANA'],
            ['id' => 'HT', 'description' => 'HAITI'],
            ['id' => 'HM', 'description' => 'HEARD AND MC DONALD ISLANDS'],
            ['id' => 'HN', 'description' => 'HONDURAS'],
            ['id' => 'HK', 'description' => 'HONG KONG'],
            ['id' => 'HU', 'description' => 'HUNGARY'],
            ['id' => 'IS', 'description' => 'ICELAND'],
            ['id' => 'IN', 'description' => 'INDIA'],
            ['id' => 'ID', 'description' => 'INDONESIA'],
            ['id' => 'IR', 'description' => 'IRAN (ISLAMIC REPUBLIC OF)'],
            ['id' => 'IQ', 'description' => 'IRAQ'],
            ['id' => 'IE', 'description' => 'IRELAND'],
            ['id' => 'IL', 'description' => 'ISRAEL'],
            ['id' => 'IT', 'description' => 'ITALY'],
            ['id' => 'JM', 'description' => 'JAMAICA'],
            ['id' => 'JP', 'description' => 'JAPAN'],
            ['id' => 'JO', 'description' => 'JORDAN'],
            ['id' => 'KZ', 'description' => 'KAZAKHSTAN'],
            ['id' => 'KE', 'description' => 'KENYA'],
            ['id' => 'KI', 'description' => 'KIRIBATI'],
            ['id' => 'KP', 'description' => 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF'],
            ['id' => 'KR', 'description' => 'KOREA, REPUBLIC OF'],
            ['id' => 'KW', 'description' => 'KUWAIT'],
            ['id' => 'KG', 'description' => 'KYRGYZSTAN'],
            ['id' => 'LA', 'description' => 'LAO PEOPLE`S DEMOCRATIC REPUBLIC'],
            ['id' => 'LV', 'description' => 'LATVIA'],
            ['id' => 'LB', 'description' => 'LEBANON'],
            ['id' => 'LS', 'description' => 'LESOTHO'],
            ['id' => 'LR', 'description' => 'LIBERIA'],
            ['id' => 'LY', 'description' => 'LIBYAN ARAB JAMAHIRIYA'],
            ['id' => 'LI', 'description' => 'LIECHTENSTEIN'],
            ['id' => 'LT', 'description' => 'LITHUANIA'],
            ['id' => 'LU', 'description' => 'LUXEMBOURG'],
            ['id' => 'MO', 'description' => 'MACAU'],
            ['id' => 'MK', 'description' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'],
            ['id' => 'MG', 'description' => 'MADAGASCAR'],
            ['id' => 'MW', 'description' => 'MALAWI'],
            ['id' => 'MY', 'description' => 'MALAYSIA'],
            ['id' => 'MV', 'description' => 'MALDIVES'],
            ['id' => 'ML', 'description' => 'MALI'],
            ['id' => 'MT', 'description' => 'MALTA'],
            ['id' => 'MH', 'description' => 'MARSHALL ISLANDS'],
            ['id' => 'MQ', 'description' => 'MARTINIQUE'],
            ['id' => 'MR', 'description' => 'MAURITANIA'],
            ['id' => 'MU', 'description' => 'MAURITIUS'],
            ['id' => 'YT', 'description' => 'MAYOTTE'],
            ['id' => 'MX', 'description' => 'MEXICO'],
            ['id' => 'FM', 'description' => 'MICRONESIA, FEDERATED STATES OF'],
            ['id' => 'MD', 'description' => 'MOLDOVA, REPUBLIC OF'],
            ['id' => 'MC', 'description' => 'MONACO'],
            ['id' => 'MN', 'description' => 'MONGOLIA'],
            ['id' => 'MS', 'description' => 'MONTSERRAT'],
            ['id' => 'MA', 'description' => 'MOROCCO'],
            ['id' => 'MZ', 'description' => 'MOZAMBIQUE'],
            ['id' => 'MM', 'description' => 'MYANMAR'],
            ['id' => 'NA', 'description' => 'NAMIBIA'],
            ['id' => 'NR', 'description' => 'NAURU'],
            ['id' => 'NP', 'description' => 'NEPAL'],
            ['id' => 'NL', 'description' => 'NETHERLANDS'],
            ['id' => 'AN', 'description' => 'NETHERLANDS ANTILLES'],
            ['id' => 'NC', 'description' => 'NEW CALEDONIA'],
            ['id' => 'NZ', 'description' => 'NEW ZEALAND'],
            ['id' => 'NI', 'description' => 'NICARAGUA'],
            ['id' => 'NE', 'description' => 'NIGER'],
            ['id' => 'NG', 'description' => 'NIGERIA'],
            ['id' => 'NU', 'description' => 'NIUE'],
            ['id' => 'NF', 'description' => 'NORFOLK ISLAND'],
            ['id' => 'MP', 'description' => 'NORTHERN MARIANA ISLANDS'],
            ['id' => 'NO', 'description' => 'NORWAY'],
            ['id' => 'OM', 'description' => 'OMAN'],
            ['id' => 'PK', 'description' => 'PAKISTAN'],
            ['id' => 'PW', 'description' => 'PALAU'],
            ['id' => 'PS', 'description' => 'PALESTINIAN TERRITORY, Occupied'],
            ['id' => 'PA', 'description' => 'PANAMA'],
            ['id' => 'PG', 'description' => 'PAPUA NEW GUINEA'],
            ['id' => 'PY', 'description' => 'PARAGUAY'],
            ['id' => 'PE', 'description' => 'PERU'],
            ['id' => 'PH', 'description' => 'PHILIPPINES'],
            ['id' => 'PN', 'description' => 'PITCAIRN'],
            ['id' => 'PL', 'description' => 'POLAND'],
            ['id' => 'PT', 'description' => 'PORTUGAL'],
            ['id' => 'PR', 'description' => 'PUERTO RICO'],
            ['id' => 'QA', 'description' => 'QATAR'],
            ['id' => 'RE', 'description' => 'REUNION'],
            ['id' => 'RO', 'description' => 'ROMANIA'],
            ['id' => 'RU', 'description' => 'RUSSIAN FEDERATION'],
            ['id' => 'RW', 'description' => 'RWANDA'],
            ['id' => 'SH', 'description' => 'SAINT HELENA'],
            ['id' => 'KN', 'description' => 'SAINT KITTS AND NEVIS'],
            ['id' => 'LC', 'description' => 'SAINT LUCIA'],
            ['id' => 'PM', 'description' => 'SAINT PIERRE AND MIQUELON'],
            ['id' => 'VC', 'description' => 'SAINT VINCENT AND THE GRENADINES'],
            ['id' => 'WS', 'description' => 'SAMOA'],
            ['id' => 'SM', 'description' => 'SAN MARINO'],
            ['id' => 'ST', 'description' => 'SAO TOME AND PRINCIPE'],
            ['id' => 'SA', 'description' => 'SAUDI ARABIA'],
            ['id' => 'SN', 'description' => 'SENEGAL'],
            ['id' => 'CS', 'description' => 'SERBIA AND MONTENEGRO'],
            ['id' => 'SC', 'description' => 'SEYCHELLES'],
            ['id' => 'SL', 'description' => 'SIERRA LEONE'],
            ['id' => 'SG', 'description' => 'SINGAPORE'],
            ['id' => 'SK', 'description' => 'SLOVAKIA'],
            ['id' => 'SI', 'description' => 'SLOVENIA'],
            ['id' => 'SB', 'description' => 'SOLOMON ISLANDS'],
            ['id' => 'SO', 'description' => 'SOMALIA'],
            ['id' => 'ZA', 'description' => 'SOUTH AFRICA'],
            ['id' => 'GS', 'description' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'],
            ['id' => 'ES', 'description' => 'SPAIN'],
            ['id' => 'LK', 'description' => 'SRI LANKA'],
            ['id' => 'SD', 'description' => 'SUDAN'],
            ['id' => 'SR', 'description' => 'SURINAME'],
            ['id' => 'SJ', 'description' => 'SVALBARD AND JAN MAYEN ISLANDS'],
            ['id' => 'SZ', 'description' => 'SWAZILAND'],
            ['id' => 'SE', 'description' => 'SWEDEN'],
            ['id' => 'CH', 'description' => 'SWITZERLAND'],
            ['id' => 'SY', 'description' => 'SYRIAN ARAB REPUBLIC'],
            ['id' => 'TW', 'description' => 'TAIWAN'],
            ['id' => 'TJ', 'description' => 'TAJIKISTAN'],
            ['id' => 'TZ', 'description' => 'TANZANIA, UNITED REPUBLIC OF'],
            ['id' => 'TH', 'description' => 'THAILAND'],
            ['id' => 'TL', 'description' => 'TIMOR-LESTE'],
            ['id' => 'TG', 'description' => 'TOGO'],
            ['id' => 'TK', 'description' => 'TOKELAU'],
            ['id' => 'TO', 'description' => 'TONGA'],
            ['id' => 'TT', 'description' => 'TRINIDAD AND TOBAGO'],
            ['id' => 'TN', 'description' => 'TUNISIA'],
            ['id' => 'TR', 'description' => 'TURKEY'],
            ['id' => 'TM', 'description' => 'TURKMENISTAN'],
            ['id' => 'TC', 'description' => 'TURKS AND CAICOS ISLANDS'],
            ['id' => 'TV', 'description' => 'TUVALU'],
            ['id' => 'UG', 'description' => 'UGANDA'],
            ['id' => 'UA', 'description' => 'UKRAINE'],
            ['id' => 'AE', 'description' => 'UNITED ARAB EMIRATES'],
            ['id' => 'GB', 'description' => 'UNITED KINGDOM'],
            ['id' => 'US', 'description' => 'UNITED STATES'],
            ['id' => 'UM', 'description' => 'UNITED STATES MINOR OUTLYING ISLANDS'],
            ['id' => 'UY', 'description' => 'URUGUAY'],
            ['id' => 'UZ', 'description' => 'UZBEKISTAN'],
            ['id' => 'VU', 'description' => 'VANUATU'],
            ['id' => 'VA', 'description' => 'VATICAN CITY STATE (HOLY SEE)'],
            ['id' => 'VE', 'description' => 'VENEZUELA'],
            ['id' => 'VN', 'description' => 'VIET NAM'],
            ['id' => 'VG', 'description' => 'VIRGIN ISLANDS (BRITISH)'],
            ['id' => 'VI', 'description' => 'VIRGIN ISLANDS (U.S.)'],
            ['id' => 'WF', 'description' => 'WALLIS AND FUTUNA ISLANDS'],
            ['id' => 'EH', 'description' => 'WESTERN SAHARA'],
            ['id' => 'YE', 'description' => 'YEMEN'],
            ['id' => 'ZM', 'description' => 'ZAMBIA'],
            ['id' => 'ZW', 'description' => 'ZIMBABWE']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
};
