<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('procedures', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('specialty_id');
            $table->string('type');
            $table->string('description');
            $table->timestamps();

            $table->foreign('specialty_id')->references('id')->on('specialties');
        });

        DB::table('procedures')->insert([
            ['id' => 1, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM CEREBRO S/C'],
            ['id' => 2, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM CEREBRO C/C'],
            ['id' => 3, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM HIPÓFISIS S/C'],
            ['id' => 4, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM HIPÓFISIS C/C'],
            ['id' => 5, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM SENOS PARANASALES S/C'],
            ['id' => 6, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM SENOS PARANASALES C/C'],
            ['id' => 7, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM MACIZO FACIAL S/C'],
            ['id' => 8, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM MACIZO FACIAL C/C'],
            ['id' => 9, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM ÓRBITAS S/C'],
            ['id' => 10, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM ÓRBITAS C/C'],
            ['id' => 11, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM OÍDOS S/C'],
            ['id' => 12, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CABEZA', 'description' => 'TEM OÍDOS C/C'],
            ['id' => 13, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM ABDOMEN SUPERIOR S/C'],
            ['id' => 14, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM ABDOMEN SUPERIOR C/C'],
            ['id' => 15, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM ABDOMEN INFERIOR S/C'],
            ['id' => 16, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM ABDOMEN INFERIOR C/C'],
            ['id' => 17, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM ABDOMEN TOTAL S/C'],
            ['id' => 18, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM ABDOMEN TOTAL C/C'],
            ['id' => 19, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM HEPÁTICO S/C'],
            ['id' => 20, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM HEPÁTICO C/C'],
            ['id' => 21, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM PELVIS S/C'],
            ['id' => 22, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE ABDOMEN', 'description' => 'TEM PELVIS C/C'],
            ['id' => 23, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE TÓRAX', 'description' => 'TEM TÓRAX S/C'],
            ['id' => 24, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE TÓRAX', 'description' => 'TEM TÓRAX C/C'],
            ['id' => 25, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE TÓRAX', 'description' => 'TEM (TÓRAX / HD) S/C'],
            ['id' => 26, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE TÓRAX', 'description' => 'TEM (TÓRAX / HD) C/C'],
            ['id' => 27, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE TÓRAX', 'description' => 'TEM MEDIASTINO S/C'],
            ['id' => 28, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE TÓRAX', 'description' => 'TEM MEDIASTINO C/C'],
            ['id' => 29, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM HOMBRO + 3D S/C'],
            ['id' => 30, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM HOMBRO + 3D C/C'],
            ['id' => 31, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM HÚMERO + 3D S/C'],
            ['id' => 32, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM HÚMERO + 3D C/C'],
            ['id' => 33, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM CODO + 3D S/C'],
            ['id' => 34, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM CODO + 3D C/C'],
            ['id' => 35, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM ANTEBRAZO + 3D S/C'],
            ['id' => 36, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM ANTEBRAZO + 3D C/C'],
            ['id' => 37, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM MUÑECA + 3D S/C'],
            ['id' => 38, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM MUÑECA + 3D C/C'],
            ['id' => 39, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM MANO + 3D S/C'],
            ['id' => 40, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS SUPERIORES', 'description' => 'TEM MANO + 3D C/C'],
            ['id' => 41, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM CADERA + 3D S/C'],
            ['id' => 42, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM CADERA + 3D C/C'],
            ['id' => 43, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM FÉMUR + 3D S/C'],
            ['id' => 44, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM FÉMUR + 3D C/C'],
            ['id' => 45, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM RODILLA + 3D S/C'],
            ['id' => 46, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM RODILLA + 3D C/C'],
            ['id' => 47, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM PIERNA + 3D S/C'],
            ['id' => 48, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM PIERNA + 3D C/C'],
            ['id' => 49, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM TOBILLOS + 3D S/C'],
            ['id' => 50, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM TOBILLOS + 3D C/C'],
            ['id' => 51, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM PIE + 3D S/C'],
            ['id' => 52, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE MIEMBROS INFERIORES', 'description' => 'TEM PIE + 3D C/C'],
            ['id' => 53, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM COLUMNA LUMBAR + 3D S/C'],
            ['id' => 54, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM COLUMNA LUMBAR + 3D C/C'],
            ['id' => 55, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM COLUMNA DORSAL + 3D S/C'],
            ['id' => 56, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM COLUMNA DORSAL + 3D C/C'],
            ['id' => 57, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM COLUMNA CERVICAL + 3D S/C'],
            ['id' => 58, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM COLUMNA CERVICAL + 3D C/C'],
            ['id' => 59, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM SACROXOCIGEA + 3D S/C'],
            ['id' => 60, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE COLUMNA', 'description' => 'TEM SACROXOCIGEA + 3D C/C'],
            ['id' => 61, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CUELLO', 'description' => 'TEM CUELLO S/C'],
            ['id' => 62, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CUELLO', 'description' => 'TEM CUELLO C/C'],
            ['id' => 63, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CUELLO', 'description' => 'TEM TIROIDEAS S/C'],
            ['id' => 64, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA DE CUELLO', 'description' => 'TEM TIROIDEAS C/C'],
            ['id' => 65, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM PULMONAR S/C'],
            ['id' => 66, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM PULMONAR C/C'],
            ['id' => 67, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM ABDOMINAL S/C'],
            ['id' => 68, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM ABDOMINAL C/C'],
            ['id' => 69, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM MIEMBROS SUPERIORES S/C'],
            ['id' => 70, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM MIEMBROS SUPERIORES C/C'],
            ['id' => 71, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM MIEMBROS INFERIORES S/C'],
            ['id' => 72, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM MIEMBROS INFERIORES C/C'],
            ['id' => 73, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM CARÓTIDA S/C'],
            ['id' => 74, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM CARÓTIDA C/C'],
            ['id' => 75, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM CEREBRAL S/C'],
            ['id' => 76, 'specialty_id' => 4, 'type' => 'TOMOGRAFIA ANGIOGRÁFICA', 'description' => 'ANGIO TEM CEREBRAL C/C'],
            ['id' => 77, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO ABDOMEN COMPLETO'],
            ['id' => 78, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO ABDOMEN SUPERIOR'],
            ['id' => 79, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO ABDOMEN INFERIOR'],
            ['id' => 80, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO CADERA'],
            ['id' => 81, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO CEREBRAL TRANSFONTANELAR'],
            ['id' => 82, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO HOMBRO'],
            ['id' => 83, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO MAMA'],
            ['id' => 84, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO MÚSCULO ESQUELÉTICO (CODO, MUÑECA, TOBILLO)'],
            ['id' => 85, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO PARED TORÁXICA Y PLEURAS'],
            ['id' => 86, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO PARTES BLANDAS'],
            ['id' => 87, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO PÉLVICA'],
            ['id' => 88, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO PRÓSTATA Y VEGIJA'],
            ['id' => 89, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO RENAL VESICAL'],
            ['id' => 90, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO RODILLA'],
            ['id' => 91, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO TESTICULAR'],
            ['id' => 92, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA', 'description' => 'ECO VESICAL'],
            ['id' => 93, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO DOPPLER DE OVARIOS, ÚTEROS Y ANEXOS (TRANSVAGINAL)'],
            ['id' => 94, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO DOPPLER OBSTÉTRICA'],
            ['id' => 95, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO DOPPLER FETAL'],
            ['id' => 96, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECOGRAFÍA 4D'],
            ['id' => 97, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO GENÉTICA'],
            ['id' => 98, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO MAMARIA'],
            ['id' => 99, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO MONITOREO DE OVULACIÓN (POR SESIÓN)'],
            ['id' => 100, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO MORFOLÓGICA'],
            ['id' => 101, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO OBSTÉTRICA'],
            ['id' => 102, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO PÉLVICA TRANSVESICAL'],
            ['id' => 103, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO PERFIL BIOFÍSICO FETAL'],
            ['id' => 104, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA GÍNECO OBSTÉTRICAS', 'description' => 'ECO TRANSVAGINAL'],
            ['id' => 105, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER ARTERIAL - MIEMBROS SUPERIORES'],
            ['id' => 106, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER ARTERIAL - MIEMBROS INFERIORES'],
            ['id' => 107, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER CAROTIDEO Y VERTEBRAL'],
            ['id' => 108, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER DE MAMAS'],
            ['id' => 109, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER DEL SISTEMA PORTA'],
            ['id' => 110, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER ESPLÉNICO'],
            ['id' => 111, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER MAMARIA'],
            ['id' => 112, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER PÉLVICA'],
            ['id' => 113, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER RENAL'],
            ['id' => 114, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER TESTICULAR'],
            ['id' => 115, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER TIROIDES'],
            ['id' => 116, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER VENOSOS - MIEMBROS SUPERIORES'],
            ['id' => 117, 'specialty_id' => 1, 'type' => 'ECOGRAFÍA DOPPLER', 'description' => 'ECO DOPPLER VENOSOS - MIEMBROS INFERIORES'],
            ['id' => 118, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'AGUJERO ÓPTICO F/P'],
            ['id' => 119, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'ARCO CIGOMÁTICO'],
            ['id' => 120, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'ARTICULACIÓN TÉMPORO MAXILAR'],
            ['id' => 121, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'ARTICULACIÓN TÉMPORO MAXILAR BILATERAL'],
            ['id' => 122, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'CAVUM'],
            ['id' => 123, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'CRÁNEO FRONTAL Y PERFIL'],
            ['id' => 124, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'HUESOS PROPIOS DE LA NARIZ F/P'],
            ['id' => 125, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'MASTOIDES'],
            ['id' => 126, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'MAXILAR SUPERIOR'],
            ['id' => 127, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'MAXILAR INFERIOR'],
            ['id' => 128, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'ÓRBITAS'],
            ['id' => 129, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'PEÑASCO CADA LADO'],
            ['id' => 130, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'SENOS PARANASALES'],
            ['id' => 131, 'specialty_id' => 3, 'type' => 'RX CABEZA Y CUELLO', 'description' => 'SILLA TURCA FRONTAL Y PERFIL'],
            ['id' => 132, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'CLAVÍCULA BILATERAL'],
            ['id' => 133, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'CLAVÍCULA UNILATERAL'],
            ['id' => 134, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'CORAZÓN Y GRANDES VASOS'],
            ['id' => 135, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'ESTERNÓN F-O'],
            ['id' => 136, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'PARRILLA COSTAL F-O'],
            ['id' => 137, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'TÓRAX F'],
            ['id' => 138, 'specialty_id' => 3, 'type' => 'RX TÓRAX', 'description' => 'TÓRAX F-P'],
            ['id' => 139, 'specialty_id' => 3, 'type' => 'RX APARATO UROGENITAL', 'description' => 'CISTOGRAFÍA'],
            ['id' => 140, 'specialty_id' => 3, 'type' => 'RX APARATO UROGENITAL', 'description' => 'HISTEROSALPINGOGRAFÍA'],
            ['id' => 141, 'specialty_id' => 3, 'type' => 'RX APARATO UROGENITAL', 'description' => 'SIMPLE DE APARATO URINARIO'],
            ['id' => 142, 'specialty_id' => 3, 'type' => 'RX APARATO UROGENITAL', 'description' => 'URETROGRAFÍA RETRÓGRADA'],
            ['id' => 143, 'specialty_id' => 3, 'type' => 'RX APARATO UROGENITAL', 'description' => 'UROGRAFÍA EXCRETORIA'],
            ['id' => 144, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'ARTICULACIÓN C1-C2'],
            ['id' => 145, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'ARTICULACIÓN COXOFEMORAL'],
            ['id' => 146, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'ARTICULACIÓN SACROILIACA BILATERAL F-20B'],
            ['id' => 147, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'ARTICULACIÓN SACROILIACA UNILATERAL'],
            ['id' => 148, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'CADERA COXOFEMORAL'],
            ['id' => 149, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'CADERA LOWESTEIN'],
            ['id' => 150, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'CADERA VAN ROSSEN'],
            ['id' => 151, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA CERVICAL F-P'],
            ['id' => 152, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA CERVICAL F-P-O'],
            ['id' => 153, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA CERVICAL FUNCIONAL'],
            ['id' => 154, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA CERVICAL DORSAL'],
            ['id' => 155, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA DORSAL F-P'],
            ['id' => 156, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA DORSAL F-P-O'],
            ['id' => 157, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA DORSAL FUNCIONAL'],
            ['id' => 158, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA DORSAL LUMBAR'],
            ['id' => 159, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA LUMBAR'],
            ['id' => 160, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA LUMBO SACRA F-P'],
            ['id' => 161, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA LUMBO SACRA F-P-O'],
            ['id' => 162, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA LUMBO SACRA FUNCIONAL'],
            ['id' => 163, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA SACRO COXIGEA F-P'],
            ['id' => 164, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'COLUMNA PANORÁMICA'],
            ['id' => 165, 'specialty_id' => 3, 'type' => 'RX COLUMNA Y PELVIS', 'description' => 'PELVIS'],
            ['id' => 166, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'ABDOMEN SIMPLE'],
            ['id' => 167, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'ABDOMEN SIMPLE DE CÚBITO Y PIE'],
            ['id' => 168, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'COLANGIOGRAFÍA POSTOPERATORIA'],
            ['id' => 169, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'COLON DOBLE CONTRASTE'],
            ['id' => 170, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'ESOFAGOGRAMA'],
            ['id' => 171, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'ESÓFAGO, ESTÓMAGO Y DUODENO CONTRASTE X2'],
            ['id' => 172, 'specialty_id' => 3, 'type' => 'RX APARATO DIGESTIVO', 'description' => 'INTESTINO DELGADO'],
            ['id' => 173, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'ANTEBRAZO F-P'],
            ['id' => 174, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'BRAZO - HÚMERO'],
            ['id' => 175, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'CALCÁNEO CORPORATIVO'],
            ['id' => 176, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'CALCÁNEO F-P'],
            ['id' => 177, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'CODO F-P'],
            ['id' => 178, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'EDAD ÓSEA'],
            ['id' => 179, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'FÉMUR'],
            ['id' => 180, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'HOMBRO'],
            ['id' => 181, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'HOMBRO COMPARATIVO'],
            ['id' => 182, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'HOMBRO FUNCIONAL UNILATERAL'],
            ['id' => 183, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'HOMBRO FUNCIONAL BILATERAL'],
            ['id' => 184, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'MANO F-O'],
            ['id' => 185, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'MANO F-LATERAL'],
            ['id' => 186, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'MEDICIÓN DE MIEMBROS'],
            ['id' => 187, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'MUÑECA F-P'],
            ['id' => 188, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'PANORÁMICO DE MIEMBROS'],
            ['id' => 189, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'PIE'],
            ['id' => 190, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'PIERNA F-P'],
            ['id' => 191, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'PIES COMPARATIVOS'],
            ['id' => 192, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'RODILLA F-P'],
            ['id' => 193, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'RÓTULO BILATERAL'],
            ['id' => 194, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'RÓTULA F-P'],
            ['id' => 195, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'SURVEY ÓSEO'],
            ['id' => 196, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'TOBILLO COMPARATIVO'],
            ['id' => 197, 'specialty_id' => 3, 'type' => 'RX EXTREMIDADES', 'description' => 'TOBILLO F-P'],
            ['id' => 198, 'specialty_id' => 3, 'type' => 'RX OTROS', 'description' => 'CUERPO EXTRAÑO'],
            ['id' => 199, 'specialty_id' => 3, 'type' => 'RX OTROS', 'description' => 'FISTULOGRAFÍA'],
            ['id' => 200, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'ÁCIDO URICO'],
            ['id' => 201, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'AMILASA'],
            ['id' => 202, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'BILIRRUBINAS TOTALES Y FRACCIONADAS'],
            ['id' => 203, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'BUN UREICO'],
            ['id' => 204, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'CALCIO LÓNICO'],
            ['id' => 205, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'CALCIO SÉRICO'],
            ['id' => 206, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'COLESTEROL HDL'],
            ['id' => 207, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'COLESTEROL LDL'],
            ['id' => 208, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'COLESTEROL TOTAL'],
            ['id' => 209, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'CPK-MB'],
            ['id' => 210, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'CREATININA'],
            ['id' => 211, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'CREATININFOSFOQUINASA (EPK TOTAL)'],
            ['id' => 212, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'DESHIDROGENASA LÁCTICA (DHL)'],
            ['id' => 213, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'ELECTROLITOS SÉRICO (NA, CL, K, CA)'],
            ['id' => 214, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'FOSFATASA ALCALINA'],
            ['id' => 215, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'FÓSFORO'],
            ['id' => 216, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'GAMMA-GLUTAMIL TRANSPEPTIDASA'],
            ['id' => 217, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'GLUCOSA BASAL'],
            ['id' => 218, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'GLUCOSA POSTPRANDIAL'],
            ['id' => 219, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'HEMOGLOBINA GLICOSILADA'],
            ['id' => 220, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'HIERRO SÉRICO'],
            ['id' => 221, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'LIPASA SÉRICO'],
            ['id' => 222, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'MAGNESIO'],
            ['id' => 223, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'PROTEINAS TOTALES FRACCIONADAS'],
            ['id' => 224, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'TOLERANCIA A LA GLUCOSA'],
            ['id' => 225, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'TRANSAMINASA OXALACÉTICA (TGO / AST)'],
            ['id' => 226, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'TRANSAMINASA PIRÚVICA (TGP/ALT)'],
            ['id' => 227, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'TRIGLICÉRIDOS'],
            ['id' => 228, 'specialty_id' => 2, 'type' => 'BIOQUIMICA', 'description' => 'ÚREA'],
            ['id' => 229, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'BK DIRECTO X1'],
            ['id' => 230, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'BK DIRECTO X2'],
            ['id' => 231, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'BK DIRECTO X3'],
            ['id' => 232, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'COPROCULTIVO'],
            ['id' => 233, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'CULTIVO DE BK'],
            ['id' => 234, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'CULTIVO DE HONGOS'],
            ['id' => 235, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'CULTIVO DE SECRECIÓN CONJUNTIVAL'],
            ['id' => 236, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'CULTIVO DE SECRECIÓN FARINGE'],
            ['id' => 237, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'CULTIVO DE SECRECIÓN'],
            ['id' => 238, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'CULTIVO DE SEMEN'],
            ['id' => 239, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'GRAM'],
            ['id' => 240, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'KOH (HONGOS)'],
            ['id' => 241, 'specialty_id' => 2, 'type' => 'MICROBIOLOGIA', 'description' => 'UROCULTIVO'],
            ['id' => 242, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'CORTISOL AM'],
            ['id' => 243, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'CORTISOL PM'],
            ['id' => 244, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'ESTRADIOL'],
            ['id' => 245, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'FHS'],
            ['id' => 246, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'INSULINA BASAL'],
            ['id' => 247, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'INSULINA POSTPRANDIAL'],
            ['id' => 248, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'LH'],
            ['id' => 249, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'PROGESTERONA'],
            ['id' => 250, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'PROLACTINA'],
            ['id' => 251, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'T3 LIBRE'],
            ['id' => 252, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'T3 TOTAL'],
            ['id' => 253, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'T4 LIBRE'],
            ['id' => 254, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'T4 TOTAL'],
            ['id' => 255, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'TESTOSTERONA TOTAL'],
            ['id' => 256, 'specialty_id' => 2, 'type' => 'HORMONAS', 'description' => 'TSH'],
            ['id' => 257, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'AGLUTINACIONES EN LÁMINA'],
            ['id' => 258, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'ANTI ESTREPTOLISINA - ASO'],
            ['id' => 259, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'BETA HCG CUALITATIVO'],
            ['id' => 260, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'BETA HCG CUANTITATIVO'],
            ['id' => 261, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'COOMBS DIRECTO'],
            ['id' => 262, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'COOMBS INDIRECTO'],
            ['id' => 263, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'FACTOR REUMATOIDEO SEMICUANTITATIVO'],
            ['id' => 264, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'HEPATITIS A IGM'],
            ['id' => 265, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'HEPATITIS B ANTÍGENO AUSTRALIANO'],
            ['id' => 266, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'INMUNOGLOBULINA E'],
            ['id' => 267, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'PCR CUANTITATIVO'],
            ['id' => 268, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'PCR LÁDEX'],
            ['id' => 269, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'RPR'],
            ['id' => 270, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'TROPONINA I'],
            ['id' => 271, 'specialty_id' => 2, 'type' => 'INMUNOLOGIA', 'description' => 'VIH'],
            ['id' => 272, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'AFP (HIGADO)'],
            ['id' => 273, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'CA 19-9 (PÁNCREAS)'],
            ['id' => 274, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'CA-125 (OVARIO)'],
            ['id' => 275, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'CEA (COLON)'],
            ['id' => 276, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'PSA ÍNDICE (PANEL COMPLETO)'],
            ['id' => 277, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'PSA LIBRE'],
            ['id' => 278, 'specialty_id' => 2, 'type' => 'MARCADORES TUMORALES', 'description' => 'PSA TOTAL'],
            ['id' => 279, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'CONSTANTES CORPUSCULARES'],
            ['id' => 280, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'FERRITINA'],
            ['id' => 281, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'FIBRINÓGENO'],
            ['id' => 282, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'GOTA GRUESA PARA PALUDISMO'],
            ['id' => 283, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'GRUPO SANGUÍNEO Y RH'],
            ['id' => 284, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'HEMATOCRITO Y HEMOGLOBINA'],
            ['id' => 285, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'HEMOGRAMA AUTOMATIZADO'],
            ['id' => 286, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'RECUENTO DE PLAQUETAS'],
            ['id' => 287, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'RETICULOCITOS'],
            ['id' => 288, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'TIEMPO DE COAGULACIÓN'],
            ['id' => 289, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'TIEMPO DE SANGRIA'],
            ['id' => 290, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'ТРТА'],
            ['id' => 291, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'TP / INR'],
            ['id' => 292, 'specialty_id' => 2, 'type' => 'HEMATOLOGIA', 'description' => 'VELOCIDAD DE SEDIMENTACIÓN'],
            ['id' => 293, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFIL CARDÍACO'],
            ['id' => 294, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFI DE COAGULACIÓN'],
            ['id' => 295, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFIL HEPÁTICO'],
            ['id' => 296, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFIL LIPÍDICO'],
            ['id' => 297, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFIL PRE-QX'],
            ['id' => 298, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFIL TIROIDEO'],
            ['id' => 299, 'specialty_id' => 2, 'type' => 'PERFILES', 'description' => 'PERFIL DEL RECIÉN NACIDO'],
            ['id' => 300, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'DEPURACIÓN DE CREATININA'],
            ['id' => 301, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'EXAMEN COMPLETO DE ORINA'],
            ['id' => 302, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'MICROALBUMINURIA 24HRS'],
            ['id' => 303, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'MICROALBUMINURIA EN ORINA SIMPLE'],
            ['id' => 304, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'PROTEINA EN ORINA SIMPLE'],
            ['id' => 305, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'PROTEINURIA CUALITATIVA'],
            ['id' => 306, 'specialty_id' => 2, 'type' => 'ORINA', 'description' => 'PROTEINURIA DE 24HRS'],
            ['id' => 307, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'COLORACIÓN VAGO (CAMPYLOBACTER)'],
            ['id' => 308, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'COPROLÓGICO FUNCIONAL'],
            ['id' => 309, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'PARASITOLÓGICO X1'],
            ['id' => 310, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'PARASITOLÓGICO X2'],
            ['id' => 311, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'PARASITOLÓGICO X3'],
            ['id' => 312, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'REACCIÓN INFLAMATORIA'],
            ['id' => 313, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'TEST DE GRAHAM'],
            ['id' => 314, 'specialty_id' => 2, 'type' => 'HECES', 'description' => 'THEVENOM (SANGRE OCULTA)'],
            ['id' => 315, 'specialty_id' => 2, 'type' => 'MARCADORES CARDIACOS', 'description' => 'CPK MB'],
            ['id' => 316, 'specialty_id' => 2, 'type' => 'MARCADORES CARDIACOS', 'description' => 'CPK TOTAL'],
            ['id' => 317, 'specialty_id' => 2, 'type' => 'MARCADORES CARDIACOS', 'description' => 'TROPONINA I'],
            ['id' => 318, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => '17 CETOESTEROIDE'],
            ['id' => 319, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => '17 HIDROXICORTICOIDE'],
            ['id' => 320, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => '17 HIDROXIPROGESTERONA'],
            ['id' => 321, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HIDROXIINDOLACÉTICO'],
            ['id' => 322, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'A.P.A (ANTIPOLIMERO ANTICUERPO)'],
            ['id' => 323, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ACETIL COLINA RECEPTOR-ANTICUERPOS'],
            ['id' => 324, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ACETILCOLINESTERASA-ANTICUERPOS'],
            ['id' => 325, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ACIDO VALPROICO'],
            ['id' => 326, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ACIDO VANILMANDELICO (ORINA 24HRS)'],
            ['id' => 327, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ACIDOS BILIARES'],
            ['id' => 328, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ACTH (AM BASAL)'],
            ['id' => 329, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ALDOLASA'],
            ['id' => 330, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANA-ANTICUERPOS ANTINUCLEARES'],
            ['id' => 331, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANCA ANTI-NEUTRÓFILOS'],
            ['id' => 332, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANDROSTENEDIONA'],
            ['id' => 333, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI-HISTONA'],
            ['id' => 334, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI CCP IGG (PÉPTIDO CÍCLICO CITRULIANO)'],
            ['id' => 335, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI MITOCONDRIALES (AMA)'],
            ['id' => 336, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI MÚSCULO LISO (ASMA)'],
            ['id' => 337, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI RNP'],
            ['id' => 338, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI SCL 70'],
            ['id' => 339, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI SM SMITH'],
            ['id' => 340, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTICOAGULANTE LÚPICO'],
            ['id' => 341, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTICUERPOS HETERÓFILOS'],
            ['id' => 342, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI DNA DS (IM)'],
            ['id' => 343, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI DNA SS AUTO ANTICUERPO'],
            ['id' => 344, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI - ESPERMATOZOIDES'],
            ['id' => 345, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI-FOSFOLIPIDOS IGG - IGM'],
            ['id' => 346, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTI-LIVERKDNEY MICROSOMALES'],
            ['id' => 347, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTITROMBINA III DOSAJE'],
            ['id' => 348, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BANDAS OLIGOCIONALES (LRC)'],
            ['id' => 349, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BARTONELLA HENSELAE IGG'],
            ['id' => 350, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BARTONELLA HENSELAE IGM'],
            ['id' => 351, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BETA 2 GLICOPROTEÍNA IGG'],
            ['id' => 352, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BETA 2 GLICOPROTEINA IGM'],
            ['id' => 353, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BETA 2 MICROGLOBULINA (ORINA 24 HRS)'],
            ['id' => 354, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BETA 2 MICROGLOBULINA SÉRICA'],
            ['id' => 355, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BETA 2 MICROGLOBULINA (ORINA SIMPLE)'],
            ['id' => 356, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'BK PCR'],
            ['id' => 357, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ROSA DE BENGALA'],
            ['id' => 358, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CA-27.29'],
            ['id' => 359, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CA-549'],
            ['id' => 360, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CA-72.4'],
            ['id' => 361, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CADENAS LIGERAS LIBRES DE SUERO'],
            ['id' => 362, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CALCITONINA - DOSAJE'],
            ['id' => 363, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CANDIDA ALBICANS ANTICUERPOS IGG'],
            ['id' => 364, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CARBAMAZEPINA (CBZ)'],
            ['id' => 365, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CARDIOLIPINA-ANTICUERPOS IGG'],
            ['id' => 366, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CARDIOLIPINA-ANTICUERPOS IGM'],
            ['id' => 367, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HIV-1 CARGA VIRAL ARN X PCR'],
            ['id' => 368, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CAROTENO SÉRICO'],
            ['id' => 369, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CENTRÓMERO-AUTOANTICUERPOS'],
            ['id' => 370, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CERULOPLASMINA'],
            ['id' => 371, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CH50 COMPLEMENTO'],
            ['id' => 372, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CHAGAS-TRIPANOZOMA-CRUZI'],
            ['id' => 373, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ANTICUERPOS'],
            ['id' => 374, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CHLAMYDIA PNEUMONIAE IGG'],
            ['id' => 375, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CHLAMYDIA PNEUMONIAE IGM'],
            ['id' => 376, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CHLAMYDIA PSITACI, IGM ANTICUERPOS'],
            ['id' => 377, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CHLAMYDIA TRACHOMATIS IGG'],
            ['id' => 378, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CHLAMYDIA TRACHOMATIS IGM'],
            ['id' => 379, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CICLOSPORINA A(L6)'],
            ['id' => 380, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CYFRA 21-1'],
            ['id' => 381, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CISTICERCUS EIA'],
            ['id' => 382, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CISTICERCUS LCR (WESTERN BLOT)'],
            ['id' => 383, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CISTICERCUS (WESTERN BLOT) SUERO'],
            ['id' => 384, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CITOMEGALOVIRUS IGG'],
            ['id' => 385, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CITOMEGALOVIRUS IGM'],
            ['id' => 386, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CITRATO EN ORINA DE 24HRS'],
            ['id' => 387, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CLONAZEPAM (RIVOTRIL)'],
            ['id' => 388, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'COBRE EN ORINA 24HRS'],
            ['id' => 389, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'COBRE SÉRICO'],
            ['id' => 390, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'COMPLEMENTO C2'],
            ['id' => 391, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'COMPLEMENTO C3'],
            ['id' => 392, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'COMPLEMENTO C4'],
            ['id' => 393, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CORTISOL EN ORINA 24HRS'],
            ['id' => 394, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CRIOGLOBULINAS - SÉROCAS'],
            ['id' => 395, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CRYPTOCOCCUS LCR - ANTICUERPOS'],
            ['id' => 396, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CRYPTOCOCCUS LCR - ANTÍGENOS'],
            ['id' => 397, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CRYPTOCOCCUS SUERO - ANTICUERPOS'],
            ['id' => 398, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'CRYPTOCOCCUS SUERO - ANTÍGENOS'],
            ['id' => 399, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'DENGUE VIRUS ANTICUERPOS IGG'],
            ['id' => 400, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'DENGUE VIRUS ANTICUERPOS IGM'],
            ['id' => 401, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'DHEA 5O4 (DEHIDROEPLANDROSTERONA)'],
            ['id' => 402, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'DIFENIL HIDANTOINA - LIBRE (L1)'],
            ['id' => 403, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'DIHIDROTESTOSTERONA'],
            ['id' => 404, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'DNA CADENA SIMPLE - ANTICUERPOS'],
            ['id' => 405, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FACTOR VIII'],
            ['id' => 406, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FACTOR IX'],
            ['id' => 407, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ELECTROFORESIS HEMOGLOBINA'],
            ['id' => 408, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ELECTROLITOS ORINA 24 HRS'],
            ['id' => 409, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ELESTASA FECAL'],
            ['id' => 410, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ENA - PERFIL AUTOINMUNE (IM)'],
            ['id' => 411, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ENDOMISIO - AUTOANTIC. (EMA) (L5)'],
            ['id' => 412, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'NSE-ENOLASA NEURONO-ESPECÍFICA (L6)'],
            ['id' => 413, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'EPSTEIN BAR VIRUS (EBNA IGM) (L5)'],
            ['id' => 414, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'EPSTEIN BAR VIRUS (EBNA IGG) (L5)'],
            ['id' => 415, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ERITROPOYETINA SÉRICA'],
            ['id' => 416, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FACTOR INTRÍNSECO - ANTICUERPOS'],
            ['id' => 417, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FACTOR V'],
            ['id' => 418, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FENÓMENO LE (CÉLULAS LE)'],
            ['id' => 419, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FÓSFORO EN ORINA'],
            ['id' => 420, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FÓSFORO EN ORINA 24HRS'],
            ['id' => 421, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FTA - ABS IGM'],
            ['id' => 422, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'FTA - ABS EN L.C.R'],
            ['id' => 423, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'GLIADINA - ANTICUERPOS'],
            ['id' => 424, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'GLUCAGON'],
            ['id' => 425, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'GLUCOSA 6 - FOSFATO DEHIDROGENASA'],
            ['id' => 426, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HELICOBACTER PILORI IGG'],
            ['id' => 427, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HELICOBACTER PILORI IGM'],
            ['id' => 428, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS A ANTICUERPOS IGG'],
            ['id' => 429, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS A ANTICUERPOS IGM'],
            ['id' => 430, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS B CARGA VIRAL'],
            ['id' => 431, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS C - HCV PCR'],
            ['id' => 432, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS C CARGA VIRAL'],
            ['id' => 433, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS C GENOTIPIFICACIÓN'],
            ['id' => 434, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS DELTA'],
            ['id' => 435, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HEPATITIS - HBE AC - ANTICUERPOS CONTRA ANTE'],
            ['id' => 436, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HERPES I - IGM'],
            ['id' => 437, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HERPES I - IGG'],
            ['id' => 438, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HERPES II - IGG'],
            ['id' => 439, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HERPES II - IGM'],
            ['id' => 440, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HIDATIDOSIS - ANTICUERPO (ELISA)'],
            ['id' => 441, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HIDATIDOSIS - WESTERN BLOT'],
            ['id' => 442, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HIV WESTERN BLOT'],
            ['id' => 443, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HLA B-27'],
            ['id' => 444, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HOMOCISTEINA SÉRICA'],
            ['id' => 445, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HORMONA DEL CRECIMIENTO'],
            ['id' => 446, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HORM. CREC. POSTESTIMULACIÓN'],
            ['id' => 447, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HORM. ANTI MULLERIANA (AMH/MIS)'],
            ['id' => 448, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HTLV 1 Y IL ANTICUERPOS (ELISA)'],
            ['id' => 449, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'HTVL I Y II WESTERN BLOT'],
            ['id' => 450, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'SATURACIÓN DE TRANSFERRINA'],
            ['id' => 451, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'INHIBINA B'],
            ['id' => 452, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'INMUNOGLOBULINA A'],
            ['id' => 453, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'INMUNOGLOBULINA G'],
            ['id' => 454, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'INMUNOGLOBULINA M'],
            ['id' => 455, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'INSULINA - ANTÍCUERPOS'],
            ['id' => 456, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'LITIO'],
            ['id' => 457, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'LITIO - TASA TRANSPORTE'],
            ['id' => 458, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'MAGNESIO 24 HRS'],
            ['id' => 459, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'METANEFRINA EN ORINA 24 HRS'],
            ['id' => 460, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'NTX TELOPÉPTIDO'],
            ['id' => 461, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'OSMOLARIDAD URINARIA (AZAR O 24 HRS)'],
            ['id' => 462, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PANEL DE ALERGIA (34 ALERGENOS) IGE ESP.'],
            ['id' => 463, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PAPERAS IGG'],
            ['id' => 464, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PAPERAS IGM'],
            ['id' => 465, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PARATOHORMONA INTACTA (PTH-INTACTA)'],
            ['id' => 466, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PÉPTIDO C'],
            ['id' => 467, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PÉPTIDO C 120'],
            ['id' => 468, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PROCALCITONINA - PCT'],
            ['id' => 469, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PROEÍNA C FUNCIONAL'],
            ['id' => 470, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PROEÍNA S FUNCIONAL'],
            ['id' => 471, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'PROTEINOGRAMA ELECTROFORÉTICO'],
            ['id' => 472, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'ROSE WAALER'],
            ['id' => 473, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'RUBEOLA - ANTICUERPOS IGM'],
            ['id' => 474, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'SIFILIS (ELISA)'],
            ['id' => 475, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'SOMATOMEDINA C (IGF-1)'],
            ['id' => 476, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'SS-A ANTICUERPOS (ANTI-RO)'],
            ['id' => 477, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'SS-A ANTICUERPOS (ANTI-LA)'],
            ['id' => 478, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TINCION KINYOUN'],
            ['id' => 479, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TORCH IGG'],
            ['id' => 480, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TORCH IGM'],
            ['id' => 481, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TOXOPLASMA GONDI IGG'],
            ['id' => 482, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TOXOPLASMA GONDI IGM'],
            ['id' => 483, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TRANSGLUTAMINASA'],
            ['id' => 484, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'AUTOANTICUERPOS IGA'],
            ['id' => 485, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TROPONINA T'],
            ['id' => 486, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'TSI ESTIMULANTE DE TIROIDES'],
            ['id' => 487, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VARICELA ZÓSTER IGG'],
            ['id' => 488, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VARICELA ZÓSTER IGM'],
            ['id' => 489, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VIH P24'],
            ['id' => 490, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VITAMINA B1'],
            ['id' => 491, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VITAMINA B12'],
            ['id' => 492, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VITAMINA B6'],
            ['id' => 493, 'specialty_id' => 2, 'type' => 'ESPECIALES', 'description' => 'VITAMINA D'],
            ['id' => 494, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'ESPERMATOGRAMA'],
            ['id' => 495, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LCR BK DIRECTO'],
            ['id' => 496, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LCR CITOQUÍMICO'],
            ['id' => 497, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LCR CULTIVO'],
            ['id' => 498, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO ASCÍTICO BK DIRECTO'],
            ['id' => 499, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO ASCÍTICO CITOQUÍMICE'],
            ['id' => 500, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO ASCÍTICO CULTIVO'],
            ['id' => 501, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO PLEURAL BK DIRECTO'],
            ['id' => 502, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO PLERUAL CITOQUÍMICO'],
            ['id' => 503, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO PLERUAL CULTIVO'],
            ['id' => 504, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO SINOVIAL BK DIRECTO'],
            ['id' => 505, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO SINOVIAL CITOQUIMIO'],
            ['id' => 506, 'specialty_id' => 2, 'type' => 'LÍQUIDOS', 'description' => 'LÍQUIDO SINOVIAL CULTIVO'],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('procedures');
    }
};
